[tool.poetry]
name = "splunktaucclib"
version = "0.0.0"
description = ""
authors = ["rfaircloth-splunk <rfaircloth@splunk.com>"]
license = "APACHE-2.0"

[tool.poetry.dependencies]
python = "^3.7"
solnlib = '^3'
splunk-sdk = "^1.6"
jinja2 = "^2"
mako= "^1"
munch= "^2"
lxml = "^4.3"
future = "^0"

[tool.poetry.dev-dependencies]
pytest = "^5.4"
pytest-splunk-addon = { version = "^1.3", extras = [ "docker" ] }
poetry-dynamic-versioning = "^0.8"

[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"