version: 2.1
orbs:
  go: circleci/go@0.2.0

jobs:
  build:
    docker:
      - image: circleci/python:3.7-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - poetry-{{ checksum "poetry.lock" }}
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "splunk_add_on_ucc_framework/UCC-UI-lib/package-lock.json" }}
      - run:
          name: Install Tools
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
            mkdir ~/.npm-global || true
            npm config set prefix '~/.npm-global'
            export PATH=~/.npm-global/bin:$PATH
            npm install -g bower
      - run:
          name: Build
          command: |
            source $HOME/.poetry/env
            export PATH=~/.npm-global/bin:$PATH
            poetry install
            poetry run poetry-dynamic-versioning
            poetry run build-ucc
            poetry build
      - save_cache:
          key: poetry-{{ checksum "poetry.lock" }}
          paths:
            - ~/.poetry
      - save_cache:
          paths:
            - ~/.npm-global # location depends on npm version
          key: npm-deps-{{ checksum "splunk_add_on_ucc_framework/UCC-UI-lib/package-lock.json" }}
      - store_artifacts:
          path: dist
      - store_artifacts:
          path: output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - dist
            - output

  test:
    docker:
      - image: circleci/python:3.7-node
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install Tools
          command: |
            pip install /tmp/workspace/dist/*
  publish:
    docker:
      - image: circleci/python:3.7-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - poetry-{{ checksum "poetry.lock" }}
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "splunk_add_on_ucc_framework/UCC-UI-lib/package-lock.json" }}
      - run:
          name: Install Tools
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
            mkdir ~/.npm-global || true
            npm config set prefix '~/.npm-global'
            export PATH=~/.npm-global/bin:$PATH
            npm install -g bower
      - run:
          name: Build
          command: |
            source $HOME/.poetry/env
            export PATH=~/.npm-global/bin:$PATH
            poetry install
            poetry run poetry-dynamic-versioning
            poetry run build-ucc
            poetry build
            poetry publish -u ${TWINE_USERNAME} -p ${TWINE_PASSWORD}
      - save_cache:
          key: poetry-{{ checksum "poetry.lock" }}
          paths:
            - ~/.poetry
      - save_cache:
          paths:
            - ~/.npm-global # location depends on npm version
          key: npm-deps-{{ checksum "splunk_add_on_ucc_framework/UCC-UI-lib/package-lock.json" }}
      - store_artifacts:
          path: dist
      - store_artifacts:
          path: output
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - dist
            - output
workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
  build_release:
    jobs:
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d*\.\d*\.\d*/
